### ISSUE TITLE
Branch switch support?

### ISSUE THREAD

**Issue by mastercoms** [ProjectBorealis/UE4GitPlugin#24]
Would switching to existing/new branches be a useful feature for the plugin?

**Comment by r3Dg** [comment]
This may be useful for certain workflows involving small, local content-related changes that don't necessitate changes to editor binaries and thus an editor restart & binary sync or compile.

I've personally done this sort of thing with:
* Local A/B testing incremental changes to binary assets in which one ultimately supplants another. (so, no merge issues)
* Prototyping things in-editor that I don't want to clutter up the remote repository with, but still want to version.

However, for this to have real use I think you'd also need to be able to make local commits and prominently display the currently checked out branch; otherwise, another git client like CLI / SourceTree / Fork would still have to be involved in the aforementioned work flows, and I'm not sure how much interest you have in expanding the plugin functionality closer to the feature set of a full-fledged graphical git client, or if the time investment is worth it.

Right now the file locking support in the plugin is a nearly exclusive and very valuable feature in that there are, to my knowledge, almost no graphical git client support for file locking (Other than very rudimentary support from Fork - though they do list all existing locks in a sub-menu which is very useful for some users, and allow maintainers to force-unlock when necessary).
