### ISSUE TITLE
Missing a setup step to ensure .uasset and .umap files are lockable

### ISSUE THREAD

**Issue by Danl2620** [ProjectBorealis/UE4GitPlugin#27]
If you don't set up `*.uasset` and `*.umap` files as lockable then the plugin won't let you "check out" those files and won't lock them.

The Readme needs text to the effect of:

Be sure to set your `*.uasset` and `*.umap` files as both LFS and lockable using:

```
git lfs track "*.uasset" --lockable
git lfs track "*.umap" --lockable
``` 

in your git repo root directory.

**Comment by Kinetomatics** [comment]
I'm testing this plugin under 4.27, I'm the repository owner and I can lock files just fine but a team member can't lock anything because he can't check the LFS file locking in Unreal:
![image](https://user-images.githubusercontent.com/70173950/157279509-f5f646cf-45f9-4c19-80a9-dc9211e6b764.png)
It's greyed out for some reason on his end and the LFS setup is installed via bash.
I added him under Github collaboration, maybe its a permissions thing, can't seem to change this though.

Any idea why?
Thanks.

**Comment by mastercoms** [comment]
Usually this means the way you distributed the plugin doesn't include the git-lfs executables. There are git lfs executables in the root of this plugin's folder.

**Comment by mastercoms** [comment]
As for the original issue, I want to make it clear through the UI that this is the case and have setup steps builtin for it.
