### ISSUE TITLE
Can't "checkin/revert" ULevel assets.

### ISSUE THREAD

**Issue by SaltyPandaCedric** [ProjectBorealis/UE4GitPlugin#72]
Hey there, 

whenever I edit a ULevel, save, checkout and later commit, it won't be "checked in" again.

That also happens with other UAssets, however ULevel's also refuse to revert:

> LogSourceControl: Warning: This operation could not complete on the following map or external packages, please unload them before retrying : /Game/XYZ/Maps/TestMaps/Enemies, /Game/XYZ/Maps/Prototype/Prototype

How do I unlock these again? :D

**Comment by mastercoms** [comment]
What UE version? What are your .gitattributes

**Comment by eXifreXi** [comment]
_EDIT: Just noticed I'm logged into a different GitHub account on this PC. :P I'm the same user as SaltyPandaCedric._

UE Version is 5.1.

GitAttributes looks like this (could be totally wrong, cause I'm usually not a Git person):

```
[attr]lock filter=lfs diff=lfs merge=binary -text lockable
[attr]lockonly lockable
[attr]lfs filter=lfs diff=lfs merge=binary -text
[attr]lfstext filter=lfs diff=lfstext merge=lfstext -text
# Unreal Engine file types.
*.uasset lock
*.umap lock
*.locres lfs
*.locmeta lfs
# Binaries
*.exe lfs
*.dll lfs
*.rcc lfs
# Icons
*.png lfs
*.ico lfs
*.icns lfs
```

**Comment by mastercoms** [comment]
I'm unfortunately unable to reproduce this, and your .gitattributes look fine. If you are able to create a minimal reproducible sample of some sort, or give me special access to your project, I would be able to investigate further. Sorry for not being of much help otherwise, though I will try to keep looking/thinking as to what could be the problem.

**Comment by sdetwiler** [comment]
I encountered this same problem using UE 5.1.1 and spent some time investigating it's cause.

I found that this code was recently added in `GitSourceControlProvider.cpp`

```
#if ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 1
bool FGitSourceControlProvider::UsesFileRevisions() const
{
	return false;
}
```

And tracing where that method is called, I see the code that configures the UE context menu in `AssetFileContextMenu.cpp` to show the "Check In" option is:

```
bool FAssetFileContextMenu::CanExecuteSCCCheckIn() const
{
	bool bUsesFileRevisions = true;

	ISourceControlProvider& SourceControlProvider = ISourceControlModule::Get().GetProvider();
	if (ISourceControlModule::Get().IsEnabled())
	{
		bUsesFileRevisions = SourceControlProvider.UsesFileRevisions();
	}
	
	return bCanExecuteSCCCheckIn && bUsesFileRevisions;
}
```

Because the added plugin code always returns `false`, the "Check In" menu option is never added.

Changing `FGitSourceControlProvider::UsesFileRevisions` to:

```
bool FGitSourceControlProvider::UsesFileRevisions() const
{
	return bUsingGitLfsLocking;
}
```

corrects the problem for me.

I'm not familiar enough with this codebase to know if this change has other, unintended consequences.

**Comment by mastercoms** [comment]
That `UsesFileRevisions` is extremely misleading and ties to a lot of random things. Seems like it's related to snapshot-based revisions like in Git vs. file-based revisions in Perforce. I think it will be safe to enable though.

**Comment by sdetwiler** [comment]
I assume others are using UE 5.1.1 so it’s odd that they haven’t encountered this, which makes me think this isn’t fully the correct solution. I’ll work with this for a while and see how it goes.

**Comment by mastercoms** [comment]
@eXifreXi @SaltyPandaCedric could you retest with the new version

**Comment by eXifreXi** [comment]
We are currently only using the plugin in a 5.2p2 Project, so unless you have a "beta" branch for that version, I would have to wait for 5.2 to fully release and for you to push an update for it :P Cause some stuff in the API changed again.

**Comment by mastercoms** [comment]
I can fix any updates for 5.2 even in preview, let me know about it and I will make the adjustments

**Comment by eXifreXi** [comment]
It would honestly be best if you could put the plugin into a 5.2p2 project, fix compile errors, and put that into some special preview branch. I also think they are actively extending the API so there might be new features available, which go beyond simple compile errors.

Would take a lot longer if I have to roll back the plugin and list the errors. I sadly don't have the time to experiment with it at the moment.

If you do find the time to fix it up for 5.2p2, let me know, otherwise, I can wait for a proper 5.2 release. I don't have a 5.1 git project at the moment.

**Comment by mastercoms** [comment]
https://github.com/ProjectBorealis/UEGitPlugin/commit/c001e9edde688b1285415e880d2b3bd0ff675212 ! Let me know if it works

**Comment by eXifreXi** [comment]
Ah lovely. I will try it out as soon as possible and report back. Currently tied up by client work. Should have some time in the afternoon (it's almost 11 am in Germany atm).
