### ISSUE TITLE
Unlocking doesn't work

### ISSUE THREAD

**Issue by dynamiquel** [ProjectBorealis/UE4GitPlugin#77]
UE version: 5.0.3
Plugin version: 3.09 (also with 3.08)
Git repo: Azure Devops

I cannot seem to get unlocking working correctly. Locks seem to work as intended and shows accordingly in Git Bash, but Reverting/Submitting within the Editor does not unlock the file. I have to unlock manually using Git Bash.

![image](https://user-images.githubusercontent.com/50085636/213874310-80772a02-3821-4f7f-98d6-1e493c4b068d.png)

**Comment by mastercoms** [comment]
Can I see your Unreal source control settings?

**Comment by eXifreXi** [comment]
FYI, the "not unlocking on submit" might be the core issue I'm also suffering from in #72 .
Or rather, this caused me to revert files manually to unlock them, and then I noticed the issue that I linked.
I'm also not sure if it affects all files because I sometimes clearly submit quite a lot of files for bigger features and only some of them are affected. Maybe only new ones (so "mark for add" ones)?

**Comment by mastercoms** [comment]
I'm going to close this issue, since from the "Checked out by:" text, it shows that the LFS Lock User needs to be updated in source control settings to "Liam Hall". With this, it will be detected as your own lock and show "Checked out" instead, and also give you all of the options. #72 is unrelated to this specific error.

I will also be upgrading the LFS lock detection to use online verification rather than requiring this error-prone user configuration, this is something I really wanted to change for a long time from the original plugin.
